// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR0tpp9qhkMd4rpkNX7zxB9NS4TqzygyU',
    appId: '1:124598624691:web:9b435a5ac0e3b29d2eabc6',
    messagingSenderId: '124598624691',
    projectId: 'chuvsu-flutter',
    authDomain: 'chuvsu-flutter.firebaseapp.com',
    storageBucket: 'chuvsu-flutter.firebasestorage.app',
    measurementId: 'G-F067DVK23D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxfMK85SA3BXoleWe1im8fzh75eeKHWDI',
    appId: '1:124598624691:android:6e0478eb27c884a82eabc6',
    messagingSenderId: '124598624691',
    projectId: 'chuvsu-flutter',
    storageBucket: 'chuvsu-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGhh_j_SR8fNrw_b5A9qvfVn11-yWvFrs',
    appId: '1:124598624691:ios:38f0ed6f73deb3592eabc6',
    messagingSenderId: '124598624691',
    projectId: 'chuvsu-flutter',
    storageBucket: 'chuvsu-flutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGhh_j_SR8fNrw_b5A9qvfVn11-yWvFrs',
    appId: '1:124598624691:ios:38f0ed6f73deb3592eabc6',
    messagingSenderId: '124598624691',
    projectId: 'chuvsu-flutter',
    storageBucket: 'chuvsu-flutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR0tpp9qhkMd4rpkNX7zxB9NS4TqzygyU',
    appId: '1:124598624691:web:f3975308db26e7992eabc6',
    messagingSenderId: '124598624691',
    projectId: 'chuvsu-flutter',
    authDomain: 'chuvsu-flutter.firebaseapp.com',
    storageBucket: 'chuvsu-flutter.firebasestorage.app',
    measurementId: 'G-6N7MMG4K6G',
  );
}
